name: Hello World
author: Nariman Ibadullaev
description: Some Description
inputs: 
  who-to-greet: 
    description: 'Who to greet'
    required: true
    default: Nariman
outputs:
  time:
    description: 'The greeting time'
runs:
  using: 'node12'
  main: 'index.js'