name: notify on issue
on:
    issues:
        types: [opened]

jobs:
    slack-message:
        runs-on: ubuntu-latest
        steps:
            - name:
              run: |
                  curl -X POST ${{ secrets.SLACK_WEBHOOK }} \ 
                  -H "Content-Type: application/json" \ 
                  -d '{"text": "new issue created: <${{github.event.issue.html_url}}|${{github.event.issue.title}}>"}'
