name: notify on release
on:
    release:
        types: [published]

jobs:
    slack-message:
        runs-on: ubuntu-latest
        steps:
            - name:
              run: |
                  curl -X POST ${{ secrets.SLACK_WEBHOOK }} -H "Content-Type: application/json"
                  --data '{"text": "new release ${{github.event.release.tag_name}} is out <${{github.event.release.html_url}}|check it out now>"}'
